import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Link from 'next/link'
import FeatureTabs from '../components/FeatureTabs'
import QuestionsAccordion from '../components/QuestionsAccordion'
import { questionsData } from '../utils/questionsData';

export default function Home() {
  return (
    <>
      <Head>
        <title>Bookmark landing page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
      </Head>
      <div className={styles.topBar}>
        <div className={styles.topBarLeft}>
        <Link href="/">
          <a><Image src="/images/logo-bookmark.svg" width={170} height={30} alt="Bookmark logo"/></a>
        </Link>
        </div>
        <nav className={styles.topBarRight}>
          <a>FEATURES</a>
          <a>PRICING</a>
          <a>CONTACT</a>
          <a className={styles.loginButton}>LOGIN</a>
        </nav>
      </div>
      <main className={styles.mainSection}>
        <div className={styles.mainSectionLeft}>
          <h1>A Simple Bookmark Manager</h1>
          <p>A clean and simple interface to organize your favourite websites. Open a new 
            browser tab and see your sites load instantly. Try it for free.</p>
          <a>Get it on Chrome</a>
          <a>Get it on Firefox</a>            
        </div>
        <div className={styles.mainSectionRight}>
          <div style={{ position: 'relative', width: '700px', height:'500px' }}>
            <Image src="/images/illustration-hero.svg" layout="fill" alt="design bookmark manager" />
          </div>
        </div>
      </main>
      <section className={styles.featuresSection}>
        <div className={styles.featuresmain}>
          <h2>Features</h2>
          <p>Our aim is to make it quick and easy for you to access your favourite websites. 
            Your bookmarks sync between your devices so you can access them on the go.</p>
        </div>
        <FeatureTabs />
      </section>   

      <section>
        <div className={styles.browsersmain}>
          <h2>Download the extension</h2>
          <p>We’ve got more browsers in the pipeline. Please do let us know if you’ve 
            got a favourite you’d like us to prioritize.</p>
        </div>
        <div className={styles.browserTabSection}>
          <div className={styles.browserTab} id={styles.browserTab1}>
            <div style={{ position: 'relative', width: '80px', height:'80px', marginLeft:"auto", marginRight:"auto" }}>
              <Image src="/images/logo-chrome.svg" layout="fill" alt="chrome logo"/>
            </div>
            <div>
              <h3>Add to Chrome</h3>
              <p>Minimum version 62</p>
            </div>
            <div>
              <Image src="/images/bg-dots.svg" width="200" height="4" alt="doted line"/>
            </div>
            <div>
              <a className={styles.browserTabButton}>Add & Install Extension</a>
            </div>
          </div>

          <div className={styles.browserTab} id={styles.browserTab2}>
            <div style={{ position: 'relative', width: '80px', height:'80px', marginLeft:"auto", marginRight:"auto" }}>
              <Image src="/images/logo-firefox.svg" layout="fill" alt="firefox logo"/>
            </div>
            <div>
              <h3>Add to Firefox</h3>
              <p>Minimum version 55</p>
            </div>
            <div>
              <Image src="/images/bg-dots.svg" width="200" height="4" alt="doted line"/>
            </div>
            <div>
              <a className={styles.browserTabButton}>Add & Install Extension</a>
            </div>
          </div>

          <div className={styles.browserTab} id={styles.browserTab3}>
            <div style={{ position: 'relative', width: '80px', height:'80px', marginLeft:"auto", marginRight:"auto" }}>
              <Image src="/images/logo-opera.svg" layout="fill" alt="opera logo"/>
            </div>
            <div>
              <h3>Add to Opera</h3>
              <p>Minimum version 46</p>
            </div>
            <div>
              <Image src="/images/bg-dots.svg" width="200" height="4" alt="doted line"/>
            </div>
            <div>
              <a className={styles.browserTabButton}>Add & Install Extension</a>
            </div>
          </div>
        </div>
      </section>
      <section className={styles.questionsSection}>
        <div className={styles.questionsMain}>
          <h2>Frequently Asked Questions</h2>
          <p>Here are some of our FAQs. If you have any other questions you’d like 
            answered please feel free to email us.</p>
        </div>
        <div className={styles.accordion}>
          {questionsData.map(({ title, content }) => ( <QuestionsAccordion key={title} title={title} content={content} />))}
        </div>
        <div className={styles.btnInfoSection}>
          <a className={styles.btninfo}>More Info</a>
        </div>
      </section>
      <section className={styles.contactSection}>
        <p>35,000+ ALREADY JOINED</p>
        <h2>Stay up-to-date with what we’re doing</h2>
        <div>
          <input placeholder="Enter your email adress"/>
          <button className={styles.contactButton}>Contact us</button>
        </div>
      </section>
      <div className={styles.bottomBar}>
        <div className={styles.bottomBarLeft}>
          <Link href="/">
            <a><Image src="/images/logo-bookmark-white.svg" width={170} height={30} alt="Bookmark logo"/></a>
           </Link>
        </div>
        <nav className={styles.bottomBarCenter}>
          <a>FEATURES</a>
          <a>PRICING</a>
          <a>CONTACT</a>
        </nav>
        <div className={styles.bottomBarRight}>
            <a><Image src="/images/icon-facebook.svg" width={30} height={30} alt="Facebook
              logo"/></a>
            <a><Image src="/images/icon-twitter.svg" width={30} height={30} alt="Twitter
              logo"/></a>
        </div>
      </div>
      <footer>

      </footer>
      
  
  
  
    </>
  )
}
